### ISSUE TITLE
Problem installing stable version

### ISSUE THREAD

**Issue by fawzibr** [kaiyou/freeposte.io#66]
I have some problems installing freeposte.io

1. The setup guide says that I can choose 'none' for the options WEBMAIL and FRONTEND. That is not working for me, if I set the options to none it just wont install giving me an error.

2. When I set the options to roundcube and nginx it starts to install but then I get a SQL error:

stable: Pulling from freeposte/admin
Digest: sha256:d32d716b6b48b47ff1b60e623adda1326e640b400c486224a91104392e6cfa2b
Status: Downloaded newer image for freeposte/admin:stable
/usr/local/lib/python3.5/site-packages/sqlalchemy/ext/declarative/api.py:173: SAWarning: Unmanaged access of declarative attribute domain_name from non-mapped class Email
  (desc.fget.__name__, cls.__name__))
/usr/local/lib/python3.5/site-packages/sqlalchemy/ext/declarative/api.py:173: SAWarning: Unmanaged access of declarative attribute email from non-mapped class Email
  (desc.fget.__name__, cls.__name__))
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: domain

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 37, in <module>
    manager.run()
  File "/usr/local/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 33, in admin
    db.session.commit()
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 767, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: domain [SQL: 'INSERT INTO domain (created_at, updated_at, comment, name, max_users, max_aliases) VALUES (?, ?, ?, ?, ?, ?)'] [parameters: ('2016-09-19', None, None, 'test-site.com', 0, 0)]

**Comment by kaiyou** [comment]
Sorry it took some time to answer.

1. Indeed ``none`` was not yet supported in stable, I just triggered builds on the Docker Hub, it should be available in a couple minutes, sorry about that.
2. I cannot reproduce your behaviour. When do you get the error exactly, could you provide some steps to reproduce? If you do not have any data yet, could you try and delete the SQLite database before reproducing?

**Comment by fawzibr** [comment]
Ok, this is whar I did:

- Created a clean ubuntu 16.04 server running on VMWare
- Installed docker (1.12.1), docker-compose (1.9.0)
- Created the /opt/freeposte directory
- Downloaded the .env + docker-compose.yml
- Since I'm testing I almost nothing on the default .env (just ROOT,FRONTEND,WEBMAIL,EXPOSE_ADMIN and added the docker internal network to RELAYNETS)
- Created self signed certificates, copied to /opt/freeposte/certs
- Started freeposte (docker-compose up -d)

I try to create the admin user using the following command (should I run the command with the services started or not? The setup does not say. I tried it with them started)
`
 docker-compose run --rm admin python manage.py admin admin mydomain.com test`

```
/usr/local/lib/python3.5/site-packages/sqlalchemy/ext/declarative/api.py:173: SAWarning: Unmanaged access of declarative attribute domain_name from non-mapped class Email
  (desc.fget.__name__, cls.__name__))
/usr/local/lib/python3.5/site-packages/sqlalchemy/ext/declarative/api.py:173: SAWarning: Unmanaged access of declarative attribute email from non-mapped class Email
  (desc.fget.__name__, cls.__name__))

```

**Comment by kaiyou** [comment]
That last warning has been an issue since the begining of Freeposte.io, I just created issue #77 about it. Still, you should be able to ignore the warning and simply use Freeposte.io.

**Comment by kaiyou** [comment]
The last remaining bug referenced as #77 was just fixed.
