### ISSUE TITLE
502 Bad gateway on admin/services

### ISSUE THREAD

**Issue by dzervas** [kaiyou/freeposte.io#78]
When I navigate to "admin/services" I get "502 Bad Gateway"

`docker logs freeposte_admin_1`
```
[2016-10-08 22:46:57 +0000] [14] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/docker/client.py", line 170, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localunixsocket/v1.24/containers/json?all=1&trunc_cmd=0&limit=-1&size=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 191, in handle_request
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.5/site-packages/gunicorn/six.py", line 625, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/app/freeposte/admin/access.py", line 35, in wrapper
    return callback(function, args, kwargs, (), {})
  File "/app/freeposte/admin/access.py", line 18, in callback
    return function(*args, **kwargs)
  File "/app/freeposte/admin/views/base.py", line 38, in services
    for brief in dockercli.containers(all=True):
  File "/usr/local/lib/python3.5/site-packages/docker/api/container.py", line 85, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/local/lib/python3.5/site-packages/docker/client.py", line 178, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.5/site-packages/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("b'client is newer than server (client API version: 1.24, server API version: 1.22)'")
```

**Comment by kaiyou** [comment]
This is due to the Docker client version being newer than the server. Do you run the recommended (or better the latest) Docker version?

**Comment by kaiyou** [comment]
Anyway I will try and catch this to display a proper error message.

**Comment by dzervas** [comment]
`docker --version`: `Docker version 1.10.3, build 1f8f545`

**Comment by kaiyou** [comment]
Indeed, the documentation specifies that you should use Docker >= 1.11. Could you try and upgrade ? (what operating system are you running on?)

Except for the services page however, using Docker 1.10 should not do you much harm.

**Comment by dzervas** [comment]
I use CoreOS, so I thought it would use the latest docker engine... I'll update and report!

**Comment by dzervas** [comment]
Ok, so I updated:
`docker version`:
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:        
 OS/Arch:      linux/amd64
```

`docker-compose version`
```
docker-compose version 1.8.1, build 878cff1
docker-py version: 1.10.3
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

I still get the errors. I also tested a lot of other stuff that give out errors:
  - ClamAV gives out error, the same with #18 (I have 1GB RAM)
  - `/services` shows the error said in the first post
  - `genkey` give `Internal Server Error`
  - deleting a domain or user gives `Internal Server Error` as well

The `Internal Server Error` is as follows (in `docker logs freeposte_admin_1`):
```
2016-10-11 11:08:56 +0000] [10] [ERROR] Error handling request /admin/domain/genkeys/dzervas.gr
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/app/freeposte/admin/access.py", line 27, in wrapper
    return callback(function, args, kwargs, dargs, dkwargs)
  File "/app/freeposte/admin/access.py", line 18, in callback
    return function(*args, **kwargs)
  File "/app/freeposte/admin/access.py", line 102, in wrapper
    form = forms.ConfirmationForm()
AttributeError: module 'freeposte.admin.forms' has no attribute 'ConfirmationForm'
```
It's the same error when trying to delete a domain/user.

**Comment by dzervas** [comment]
Contents of `/etc/os-release`:

```
NAME=CoreOS
ID=coreos
VERSION=1185.1.0
VERSION_ID=1185.1.0
BUILD_ID=2016-10-05-0500
PRETTY_NAME="CoreOS 1185.1.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by curry684** [comment]
> I use CoreOS, so I thought it would use the latest docker engine...

In practice even CoreOS Alpha takes weeks to adopt the latest Docker version. Beta is still on 1.11.2 and Stable on 1.10.3 indeed. It is of course called 'stable' because it doesn't adopt the latest fads immediately  ;)

**Comment by kaiyou** [comment]
The internal errors are all related to a missing form, which is weird given that the object exists and I cannot seem to reproduce. Which Freeposte version are you running? If you are running ``latest``, could you try and pull again, maybe you pulled at a time I was still fixing bugs related to the internationalization.

I will try and reproduce the ClamAV error.

Regarding the original bug, after you upgraded, could you check that the version numbers in the error log are still the same?

```
(client API version: 1.24, server API version: 1.22)
```

**Comment by dzervas** [comment]
I updated docker and everything works! :)
Note for CoreOS users: You need to update to `alpha` release.
Thank you!
